### ISSUE TITLE
Checking the authorization

### ISSUE THREAD

**Issue by Modius22** [ilunos/docker-agent#2]
Check if certain API functions can be restricted with roles/groups from Keycloak.

For example..: 
- Read role/group may only get
- Write/execute role/group may create, start, stop, build containers,
- Role/Group Remove may delete images/containers

**Comment by Nanabell** [comment]
Added support for Keycloak Authentication & Authorization. 

application.yml security config:
```yml
    oauth2:
      enabled: true                       # Set to false to disable oauth2 / keycloak authentication.
      clients:
        keycloak:
          client-id: docker-agent         # Client id of the client generated in keycloak
          client-secret: <client-secret>  # Put your generated client secret here if you are using access_type = confidential
          openid:
            issuer: <http://issuer/url>   # Url to the Issuer, includes the Realm
```

Currently! the agent requires a client with the name `docker-agent` to be created in the realm and the following 3 roles defined in the client: 
- Admin
- Manager
- User
Admin & Manager must be defined as composite Roles and include the lower tier. i.e Admin includes Manager and Manager includes User

I've also included a Dummy Basic Auth Provider which is disabled by default 
```yml
    basic-auth:
      enabled: false                      # Enable the builtin admin:admin development account.
```
Enabling this will allow login with admin:admin | manager:manager | user:user for their respective roles.
Username passwords cannot be changed and should only be used for local testing and left disabled on production systems.
